[package]
name = "shuasm"
version = "0.1.0"
authors = ["longfangsong <longfangsong@icloud.com>"]
edition = "2021"

[dependencies]
parse_int = "0.6.0"
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"
tera = "1.15.0"
