[package]
name = "my-riscv-asm"
version = "0.1.0"
authors = ["longfangsong <longfangsong@icloud.com>"]
edition = "2018"

[dependencies]
tinytemplate = "1.0.2"
serde_derive = "1.0"
serde = "1.0"
lazy_static = "1.3.0"