name: Build docker

on:
  push:
    branches:
      - main
jobs:
  build-docker:
    runs-on: ubuntu-latest
    name: Build and upload docker image
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        docker build . -t ${{ secrets.DOCKER_USERNAME }}/shuasm
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        docker push ${{ secrets.DOCKER_USERNAME }}/shuasm
    